// Disclaimer: This a ChatGPT generated sample data.

import { ApplicantData } from "@/types/ApplicantData";

export const data: ApplicantData[] = [
  {
    // applicationId: string (Firestore - auto generated)
    dateSubmitted: new Date("2024-09-14"),
    applicationStatus: "Unreviewed",
    isApplicationStatusEdited: false,
    isEdited: false,
    isDeleted: false,
    activeEmail: "johndoe@gmail.com",
    lastName: "Doe",
    firstName: "John",
    age: 25,
    gender: "Male",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: new Date("1999-01-15"),
    birthplace: "Cebu City",
    civilStatus: "Single",
    birthRank: "2nd",
    numBrothers: 1,
    numSisters: 2,
    numCITBrothersSisters: 0,
    homeAddress: "1234 Mango St., Cebu City",
    cityAddress: "4567 Banana Ave., Cebu City",
    facebookURL: "https://facebook.com/johndoe",
    mobileNumber: "09123456789",
    fatherName: "Doe, Michael J.",
    fatherAge: 55,
    fatherBirthplace: "Manila",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Engineer",
    motherName: "Doe, Jane A.",
    motherAge: 53,
    motherBirthplace: "Davao City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Teacher",
    prevCourse: "BS Computer Science",
    lastSchool: "XYZ University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "ABC St., Cebu City",
    hsSchoolName: "XYZ High School",
    hsSchoolAddress: "Cebu City",
    hsYearGraduated: "2017",
    elemSchoolName: "ABC Elementary School",
    elemSchoolAddress: "Cebu City",
    elemYearGraduated: "2013",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSECE",
    contactName: "Smith, Anna B.",
    relation: "Sister",
    contactAddress: "7890 Orange St., Cebu City",
    contactNumber: "09198765432",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "TOR, COE",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition is good as it drives us to achieve our goals.",
    secondQuestion: "Yes, honesty builds trust, which is essential for relationships.",
    thirdQuestion: "Life is what we make it, so we should strive to live it well.",
    fourthQuestion: "Reading enhances knowledge and opens doors to opportunities.",
    fifthQuestion: "Experience teaches valuable lessons that theory alone cannot provide.",
  },
   
  // Additional entries...
];
