// Disclaimer: This a ChatGPT generated sample data.

import { ApplicantData } from "@/types/ApplicantData";

export const data: ApplicantData[] = [
  {
    dateSubmitted: new Date("2024-08-30"),
    applicationStatus: "Unreviewed",
    isEdited: false,
    activeEmail: "johndoe@gmail.com",
    lastName: "Doe",
    firstName: "John",
    age: 25,
    gender: "Male",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: new Date("1999-01-15"),
    birthplace: "Cebu City",
    civilStatus: "Single",
    birthRank: "2nd",
    numBrothers: 1,
    numSisters: 2,
    numCITBrothersSisters: 0,
    homeAddress: "1234 Mango St., Cebu City",
    cityAddress: "4567 Banana Ave., Cebu City",
    facebookURL: "https://facebook.com/johndoe",
    mobileNumber: "09123456789",
    fatherName: "Doe, Michael J.",
    fatherAge: 55,
    fatherBirthplace: "Manila",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Engineer",
    motherName: "Doe, Jane A.",
    motherAge: 53,
    motherBirthplace: "Davao City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Teacher",
    prevCourse: "BS Computer Science",
    lastSchool: "XYZ University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "ABC St., Cebu City",
    hsSchoolName: "XYZ High School",
    hsSchoolAddress: "Cebu City",
    hsYearGraduated: "2017",
    elemSchoolName: "ABC Elementary School",
    elemSchoolAddress: "Cebu City",
    elemYearGraduated: "2013",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSECE",
    contactName: "Smith, Anna B.",
    relation: "Sister",
    contactAddress: "7890 Orange St., Cebu City",
    contactNumber: "09198765432",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "TOR, COE",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition is good as it drives us to achieve our goals.",
    secondQuestion: "Yes, honesty builds trust, which is essential for relationships.",
    thirdQuestion: "Life is what we make it, so we should strive to live it well.",
    fourthQuestion: "Reading enhances knowledge and opens doors to opportunities.",
    fifthQuestion: "Experience teaches valuable lessons that theory alone cannot provide.",
  },
  {
    dateSubmitted: new Date("2024-9-7"),
    applicationStatus: "Transferred",
    isEdited: true,
    activeEmail: "janesmith@gmail.com",
    lastName: "Smith",
    firstName: "Jane",
    age: 22,
    gender: "Female",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: new Date("2002-03-22"),
    birthplace: "Mandaue City",
    civilStatus: "Single",
    birthRank: "1st",
    numBrothers: 0,
    numSisters: 1,
    numCITBrothersSisters: 0,
    homeAddress: "7890 Pine St., Mandaue City",
    cityAddress: "6789 Apple St., Cebu City",
    facebookURL: "https://facebook.com/janesmith",
    mobileNumber: "09112223344",
    fatherName: "Smith, Robert L.",
    fatherAge: 50,
    fatherBirthplace: "Cebu City",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "High School Graduate",
    fatherOccupation: "Driver",
    motherName: "Smith, Maria P.",
    motherAge: 48,
    motherBirthplace: "Cebu City",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "High School Graduate",
    motherOccupation: "Housewife",
    prevCourse: "",
    lastSchool: "DEF High School",
    schoolYear: "2020",
    schoolType: "Public",
    prevSchoolAddress: "DEF St., Mandaue City",
    hsSchoolName: "DEF High School",
    hsSchoolAddress: "Mandaue City",
    hsYearGraduated: "2020",
    elemSchoolName: "GHI Elementary School",
    elemSchoolAddress: "Mandaue City",
    elemYearGraduated: "2016",
    progChoice1: "BSN",
    progChoice2: "BSED",
    progChoice3: "BSBA",
    contactName: "Johnson, Mark A.",
    relation: "Uncle",
    contactAddress: "5678 Maple St., Cebu City",
    contactNumber: "09115556677",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set B",
    firstQuestion: "Ambition can be both good and bad depending on its direction.",
    secondQuestion: "Honesty is the foundation of trust and integrity.",
    thirdQuestion: "We shape our lives by the decisions we make.",
    fourthQuestion: "Reading is essential for personal and professional growth.",
    fifthQuestion: "Experience provides practical knowledge that complements theoretical learning.",
  },
  {
    dateSubmitted: new Date("2024-9-6"),
    applicationStatus: "Transferred",
    isEdited: true,
    activeEmail: "michaeltan@gmail.com",
    lastName: "Tan",
    firstName: "Michael",
    age: 23,
    gender: "Male",
    nationality: "Filipino",
    religion: "Buddhist",
    birthdate: new Date("2001-08-14"),
    birthplace: "Quezon City",
    civilStatus: "Single",
    birthRank: "1st",
    numBrothers: 0,
    numSisters: 0,
    numCITBrothersSisters: 0,
    homeAddress: "1356 Maple St., Quezon City",
    cityAddress: "2468 Oak Ave., Quezon City",
    facebookURL: "https://facebook.com/michaeltan",
    mobileNumber: "09187654321",
    fatherName: "Tan, Peter Y.",
    fatherAge: 60,
    fatherBirthplace: "Quezon City",
    fatherNationality: "Filipino",
    fatherReligion: "Buddhist",
    fatherEducation: "College Graduate",
    fatherOccupation: "Businessman",
    motherName: "Tan, Grace M.",
    motherAge: 58,
    motherBirthplace: "Makati City",
    motherNationality: "Filipino",
    motherReligion: "Buddhist",
    motherEducation: "College Graduate",
    motherOccupation: "Homemaker",
    prevCourse: "BSBA",
    lastSchool: "LMN University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "123 Blue St., Quezon City",
    hsSchoolName: "LMN High School",
    hsSchoolAddress: "Quezon City",
    hsYearGraduated: "2018",
    elemSchoolName: "PQR Elementary School",
    elemSchoolAddress: "Quezon City",
    elemYearGraduated: "2014",
    progChoice1: "BSBA",
    progChoice2: "BSA",
    progChoice3: "BSHRM",
    contactName: "Santos, Julie R.",
    relation: "Aunt",
    contactAddress: "567 Willow St., Quezon City",
    contactNumber: "09191112222",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set C",
    firstQuestion: "Ambition leads to success if guided by the right values.",
    secondQuestion: "Honesty builds credibility in every relationship.",
    thirdQuestion: "Our actions today define our future.",
    fourthQuestion: "Reading broadens horizons and encourages critical thinking.",
    fifthQuestion: "Practical experience teaches lessons that textbooks cannot provide."
  },
  {
    dateSubmitted: new Date("2024-9-1"),
    applicationStatus: "INC Document",
    isEdited: false,
    activeEmail: "alicegarcia@gmail.com",
    lastName: "Garcia",
    firstName: "Alice",
    age: 24,
    gender: "Female",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: new Date("2000-05-12"),
    birthplace: "Davao City",
    civilStatus: "Single",
    birthRank: "3rd",
    numBrothers: 2,
    numSisters: 1,
    numCITBrothersSisters: 0,
    homeAddress: "4321 Palm St., Davao City",
    cityAddress: "5432 Oak Ave., Davao City",
    facebookURL: "https://facebook.com/alicegarcia",
    mobileNumber: "09112345678",
    fatherName: "Garcia, Paul E.",
    fatherAge: 52,
    fatherBirthplace: "Davao City",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Architect",
    motherName: "Garcia, Linda P.",
    motherAge: 50,
    motherBirthplace: "Cebu City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Lawyer",
    prevCourse: "BSIT",
    lastSchool: "JKL University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "456 Yellow St., Davao City",
    hsSchoolName: "JKL High School",
    hsSchoolAddress: "Davao City",
    hsYearGraduated: "2017",
    elemSchoolName: "STU Elementary School",
    elemSchoolAddress: "Davao City",
    elemYearGraduated: "2013",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSIS",
    contactName: "Reyes, Carla B.",
    relation: "Cousin",
    contactAddress: "876 Blue St., Davao City",
    contactNumber: "09192223344",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "TOR",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition is the fuel that drives personal progress.",
    secondQuestion: "Honesty is essential for maintaining personal integrity.",
    thirdQuestion: "We control our destiny through the decisions we make.",
    fourthQuestion: "Reading is vital for both personal and professional growth.",
    fifthQuestion: "Experience provides deeper understanding than theoretical knowledge alone."
  },
  {
    dateSubmitted: new Date("2024-9-9"),
    applicationStatus: "Unreviewed",
    isEdited: true,
    activeEmail: "carlobautista@gmail.com",
    lastName: "Bautista",
    firstName: "Carlo",
    age: 21,
    gender: "Male",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: new Date("2003-12-01"),
    birthplace: "Taguig City",
    civilStatus: "Single",
    birthRank: "4th",
    numBrothers: 2,
    numSisters: 0,
    numCITBrothersSisters: 0,
    homeAddress: "678 Pine St., Taguig City",
    cityAddress: "789 Cedar Ave., Taguig City",
    facebookURL: "https://facebook.com/carlobautista",
    mobileNumber: "09124445566",
    fatherName: "Bautista, Ronald F.",
    fatherAge: 48,
    fatherBirthplace: "Taguig City",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "College Graduate",
    fatherOccupation: "Police Officer",
    motherName: "Bautista, Celia G.",
    motherAge: 46,
    motherBirthplace: "Makati City",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "College Graduate",
    motherOccupation: "Nurse",
    prevCourse: "BSA",
    lastSchool: "NOP University",
    schoolYear: "2022",
    schoolType: "Private",
    prevSchoolAddress: "789 Red St., Taguig City",
    hsSchoolName: "NOP High School",
    hsSchoolAddress: "Taguig City",
    hsYearGraduated: "2020",
    elemSchoolName: "VWX Elementary School",
    elemSchoolAddress: "Taguig City",
    elemYearGraduated: "2016",
    progChoice1: "BSA",
    progChoice2: "BSAcT",
    progChoice3: "BSE",
    contactName: "Dela Cruz, Maria S.",
    relation: "Neighbor",
    contactAddress: "654 Pine St., Taguig City",
    contactNumber: "09115557788",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set B",
    firstQuestion: "Ambition inspires people to push beyond their limits.",
    secondQuestion: "Honesty is the foundation of trust and respect.",
    thirdQuestion: "Our life’s journey is determined by the choices we make.",
    fourthQuestion: "Reading opens up new perspectives and knowledge.",
    fifthQuestion: "Practical experience builds a stronger understanding of theoretical concepts."
  },
  {
    dateSubmitted: new Date("2024-09-10"),
    applicationStatus: "Declined",
    isEdited: false,
    activeEmail: "emilyrodriguez@gmail.com",
    lastName: "Rodriguez",
    firstName: "Emily",
    age: 27,
    gender: "Female",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: new Date("1997-02-14"),
    birthplace: "Cebu City",
    civilStatus: "Married",
    birthRank: "1st",
    numBrothers: 2,
    numSisters: 1,
    numCITBrothersSisters: 0,
    homeAddress: "123 Mango St., Cebu City",
    cityAddress: "456 Orange St., Cebu City",
    facebookURL: "https://facebook.com/emilyrodriguez",
    mobileNumber: "09127778888",
    fatherName: "Rodriguez, Albert M.",
    fatherAge: 58,
    fatherBirthplace: "Cebu City",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "College Graduate",
    fatherOccupation: "Doctor",
    motherName: "Rodriguez, Maria L.",
    motherAge: 56,
    motherBirthplace: "Cebu City",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "College Graduate",
    motherOccupation: "Pharmacist",
    prevCourse: "BS Nursing",
    lastSchool: "XYZ University",
    schoolYear: "2018",
    schoolType: "Private",
    prevSchoolAddress: "123 Mango St., Cebu City",
    hsSchoolName: "ABC High School",
    hsSchoolAddress: "Cebu City",
    hsYearGraduated: "2014",
    elemSchoolName: "XYZ Elementary School",
    elemSchoolAddress: "Cebu City",
    elemYearGraduated: "2010",
    progChoice1: "BSN",
    progChoice2: "BSED",
    progChoice3: "BSBA",
    contactName: "Garcia, Juan M.",
    relation: "Friend",
    contactAddress: "456 Banana St., Cebu City",
    contactNumber: "09125556666",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set C",
    firstQuestion: "Ambition drives progress but must be tempered by values.",
    secondQuestion: "Honesty nurtures trust and healthy relationships.",
    thirdQuestion: "Our actions reflect our future.",
    fourthQuestion: "Reading allows for continuous self-improvement.",
    fifthQuestion: "Practical experiences teach valuable lessons that books cannot."
  },
  {
    dateSubmitted: new Date("2024-09-11"),
    applicationStatus: "Declined",
    isEdited: false,
    activeEmail: "joseramos@gmail.com",
    lastName: "Ramos",
    firstName: "Jose",
    age: 29,
    gender: "Male",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: new Date("1995-05-22"),
    birthplace: "Manila",
    civilStatus: "Single",
    birthRank: "2nd",
    numBrothers: 1,
    numSisters: 2,
    numCITBrothersSisters: 0,
    homeAddress: "123 Pine St., Manila",
    cityAddress: "789 Cedar Ave., Manila",
    facebookURL: "https://facebook.com/joseramos",
    mobileNumber: "09119998888",
    fatherName: "Ramos, Manuel R.",
    fatherAge: 61,
    fatherBirthplace: "Manila",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "College Graduate",
    fatherOccupation: "Lawyer",
    motherName: "Ramos, Luz P.",
    motherAge: 59,
    motherBirthplace: "Manila",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "College Graduate",
    motherOccupation: "Teacher",
    prevCourse: "BSBA",
    lastSchool: "ABC University",
    schoolYear: "2016",
    schoolType: "Private",
    prevSchoolAddress: "456 Maple St., Manila",
    hsSchoolName: "DEF High School",
    hsSchoolAddress: "Manila",
    hsYearGraduated: "2012",
    elemSchoolName: "GHI Elementary School",
    elemSchoolAddress: "Manila",
    elemYearGraduated: "2008",
    progChoice1: "BSA",
    progChoice2: "BSBA",
    progChoice3: "BSE",
    contactName: "Reyes, Carlos P.",
    relation: "Uncle",
    contactAddress: "789 Willow St., Manila",
    contactNumber: "09118887777",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition fosters growth and personal achievement.",
    secondQuestion: "Honesty creates a foundation of respect and trust.",
    thirdQuestion: "Life is shaped by our decisions and perseverance.",
    fourthQuestion: "Reading expands horizons and knowledge.",
    fifthQuestion: "Experience provides invaluable real-world insights."
  },
  {
    dateSubmitted: new Date("2024-09-12"),
    applicationStatus: "Unreviewed",
    isEdited: true,
    activeEmail: "markgonzalez@gmail.com",
    lastName: "Gonzalez",
    firstName: "Mark",
    age: 20,
    gender: "Male",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: new Date("2004-07-05"),
    birthplace: "Baguio City",
    civilStatus: "Single",
    birthRank: "3rd",
    numBrothers: 2,
    numSisters: 0,
    numCITBrothersSisters: 0,
    homeAddress: "234 Peach St., Baguio City",
    cityAddress: "567 Apple St., Baguio City",
    facebookURL: "https://facebook.com/markgonzalez",
    mobileNumber: "09116667777",
    fatherName: "Gonzalez, Pedro M.",
    fatherAge: 52,
    fatherBirthplace: "Baguio City",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Businessman",
    motherName: "Gonzalez, Ana L.",
    motherAge: 50,
    motherBirthplace: "Baguio City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Businesswoman",
    prevCourse: "BSIT",
    lastSchool: "LMN University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "789 Red St., Baguio City",
    hsSchoolName: "LMN High School",
    hsSchoolAddress: "Baguio City",
    hsYearGraduated: "2020",
    elemSchoolName: "PQR Elementary School",
    elemSchoolAddress: "Baguio City",
    elemYearGraduated: "2016",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSIS",
    contactName: "Garcia, Juan L.",
    relation: "Friend",
    contactAddress: "456 Yellow St., Baguio City",
    contactNumber: "09114443333",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set B",
    firstQuestion: "Ambition pushes people towards their goals.",
    secondQuestion: "Honesty is the core of trust in any relationship.",
    thirdQuestion: "We are defined by the choices we make in life.",
    fourthQuestion: "Reading opens doors to endless knowledge.",
    fifthQuestion: "Practical experience is the best teacher for life skills."
}
  
  // Additional entries...
];
