// Disclaimer: This a ChatGPT generated sample data.

import { ApplicantData } from "@/types/ApplicantData";

export const data: ApplicantData[] = [
  {
    applicationId: "A001",
    dateSubmitted: new Date("2024-08-30"),
    applicationStatus: "Unreviewed",
    isEdited: false,
    activeEmail: "johndoe@gmail.com",
    lastName: "Doe",
    firstName: "John",
    age: 25,
    gender: "Male",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: "1999-01-15",
    birthplace: "Cebu City",
    civilStatus: "Single",
    birthRank: "2nd",
    numBrothers: 1,
    numSisters: 2,
    numCITBrothersSisters: 0,
    homeAddress: "1234 Mango St., Cebu City",
    cityAddress: "4567 Banana Ave., Cebu City",
    facebookURL: "https://facebook.com/johndoe",
    mobileNumber: "09123456789",
    fatherName: "Doe, Michael J.",
    fatherAge: 55,
    fatherBirthplace: "Manila",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Engineer",
    motherName: "Doe, Jane A.",
    motherAge: 53,
    motherBirthplace: "Davao City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Teacher",
    prevCourse: "BS Computer Science",
    lastSchool: "XYZ University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "ABC St., Cebu City",
    hsSchoolName: "XYZ High School",
    hsSchoolAddress: "Cebu City",
    hsYearGraduated: "2017",
    elemSchoolName: "ABC Elementary School",
    elemSchoolAddress: "Cebu City",
    elemYearGraduated: "2013",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSECE",
    contactName: "Smith, Anna B.",
    relation: "Sister",
    contactAddress: "7890 Orange St., Cebu City",
    contactNumber: "09198765432",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "TOR, COE",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition is good as it drives us to achieve our goals.",
    secondQuestion: "Yes, honesty builds trust, which is essential for relationships.",
    thirdQuestion: "Life is what we make it, so we should strive to live it well.",
    fourthQuestion: "Reading enhances knowledge and opens doors to opportunities.",
    fifthQuestion: "Experience teaches valuable lessons that theory alone cannot provide.",
  },
  {
    applicationId: "A002",
    dateSubmitted: new Date("2024-9-7"),
    applicationStatus: "Transferred",
    isEdited: true,
    activeEmail: "janesmith@gmail.com",
    lastName: "Smith",
    firstName: "Jane",
    age: 22,
    gender: "Female",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: "2002-03-22",
    birthplace: "Mandaue City",
    civilStatus: "Single",
    birthRank: "1st",
    numBrothers: 0,
    numSisters: 1,
    numCITBrothersSisters: 0,
    homeAddress: "7890 Pine St., Mandaue City",
    cityAddress: "6789 Apple St., Cebu City",
    facebookURL: "https://facebook.com/janesmith",
    mobileNumber: "09112223344",
    fatherName: "Smith, Robert L.",
    fatherAge: 50,
    fatherBirthplace: "Cebu City",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "High School Graduate",
    fatherOccupation: "Driver",
    motherName: "Smith, Maria P.",
    motherAge: 48,
    motherBirthplace: "Cebu City",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "High School Graduate",
    motherOccupation: "Housewife",
    prevCourse: "",
    lastSchool: "DEF High School",
    schoolYear: "2020",
    schoolType: "Public",
    prevSchoolAddress: "DEF St., Mandaue City",
    hsSchoolName: "DEF High School",
    hsSchoolAddress: "Mandaue City",
    hsYearGraduated: "2020",
    elemSchoolName: "GHI Elementary School",
    elemSchoolAddress: "Mandaue City",
    elemYearGraduated: "2016",
    progChoice1: "BSN",
    progChoice2: "BSED",
    progChoice3: "BSBA",
    contactName: "Johnson, Mark A.",
    relation: "Uncle",
    contactAddress: "5678 Maple St., Cebu City",
    contactNumber: "09115556677",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set B",
    firstQuestion: "Ambition can be both good and bad depending on its direction.",
    secondQuestion: "Honesty is the foundation of trust and integrity.",
    thirdQuestion: "We shape our lives by the decisions we make.",
    fourthQuestion: "Reading is essential for personal and professional growth.",
    fifthQuestion: "Experience provides practical knowledge that complements theoretical learning.",
  },
  {
    applicationId: "A003",
    dateSubmitted: new Date("2024-9-6"),
    applicationStatus: "Transferred",
    isEdited: true,
    activeEmail: "michaeltan@gmail.com",
    lastName: "Tan",
    firstName: "Michael",
    age: 23,
    gender: "Male",
    nationality: "Filipino",
    religion: "Buddhist",
    birthdate: "2001-08-14",
    birthplace: "Quezon City",
    civilStatus: "Single",
    birthRank: "1st",
    numBrothers: 0,
    numSisters: 0,
    numCITBrothersSisters: 0,
    homeAddress: "1356 Maple St., Quezon City",
    cityAddress: "2468 Oak Ave., Quezon City",
    facebookURL: "https://facebook.com/michaeltan",
    mobileNumber: "09187654321",
    fatherName: "Tan, Peter Y.",
    fatherAge: 60,
    fatherBirthplace: "Quezon City",
    fatherNationality: "Filipino",
    fatherReligion: "Buddhist",
    fatherEducation: "College Graduate",
    fatherOccupation: "Businessman",
    motherName: "Tan, Grace M.",
    motherAge: 58,
    motherBirthplace: "Makati City",
    motherNationality: "Filipino",
    motherReligion: "Buddhist",
    motherEducation: "College Graduate",
    motherOccupation: "Homemaker",
    prevCourse: "BSBA",
    lastSchool: "LMN University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "123 Blue St., Quezon City",
    hsSchoolName: "LMN High School",
    hsSchoolAddress: "Quezon City",
    hsYearGraduated: "2018",
    elemSchoolName: "PQR Elementary School",
    elemSchoolAddress: "Quezon City",
    elemYearGraduated: "2014",
    progChoice1: "BSBA",
    progChoice2: "BSA",
    progChoice3: "BSHRM",
    contactName: "Santos, Julie R.",
    relation: "Aunt",
    contactAddress: "567 Willow St., Quezon City",
    contactNumber: "09191112222",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set C",
    firstQuestion: "Ambition leads to success if guided by the right values.",
    secondQuestion: "Honesty builds credibility in every relationship.",
    thirdQuestion: "Our actions today define our future.",
    fourthQuestion: "Reading broadens horizons and encourages critical thinking.",
    fifthQuestion: "Practical experience teaches lessons that textbooks cannot provide."
  },
  {
    applicationId: "A004",
    dateSubmitted: new Date("2024-9-1"),
    applicationStatus: "INC Document",
    isEdited: false,
    activeEmail: "alicegarcia@gmail.com",
    lastName: "Garcia",
    firstName: "Alice",
    age: 24,
    gender: "Female",
    nationality: "Filipino",
    religion: "Christian",
    birthdate: "2000-05-12",
    birthplace: "Davao City",
    civilStatus: "Single",
    birthRank: "3rd",
    numBrothers: 2,
    numSisters: 1,
    numCITBrothersSisters: 0,
    homeAddress: "4321 Palm St., Davao City",
    cityAddress: "5432 Oak Ave., Davao City",
    facebookURL: "https://facebook.com/alicegarcia",
    mobileNumber: "09112345678",
    fatherName: "Garcia, Paul E.",
    fatherAge: 52,
    fatherBirthplace: "Davao City",
    fatherNationality: "Filipino",
    fatherReligion: "Christian",
    fatherEducation: "College Graduate",
    fatherOccupation: "Architect",
    motherName: "Garcia, Linda P.",
    motherAge: 50,
    motherBirthplace: "Cebu City",
    motherNationality: "Filipino",
    motherReligion: "Christian",
    motherEducation: "College Graduate",
    motherOccupation: "Lawyer",
    prevCourse: "BSIT",
    lastSchool: "JKL University",
    schoolYear: "2023",
    schoolType: "Private",
    prevSchoolAddress: "456 Yellow St., Davao City",
    hsSchoolName: "JKL High School",
    hsSchoolAddress: "Davao City",
    hsYearGraduated: "2017",
    elemSchoolName: "STU Elementary School",
    elemSchoolAddress: "Davao City",
    elemYearGraduated: "2013",
    progChoice1: "BSIT",
    progChoice2: "BSCS",
    progChoice3: "BSIS",
    contactName: "Reyes, Carla B.",
    relation: "Cousin",
    contactAddress: "876 Blue St., Davao City",
    contactNumber: "09192223344",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "TOR",
    photoWithID: null,
    examSet: "Set A",
    firstQuestion: "Ambition is the fuel that drives personal progress.",
    secondQuestion: "Honesty is essential for maintaining personal integrity.",
    thirdQuestion: "We control our destiny through the decisions we make.",
    fourthQuestion: "Reading is vital for both personal and professional growth.",
    fifthQuestion: "Experience provides deeper understanding than theoretical knowledge alone."
  },
  {
    applicationId: "A005",
    dateSubmitted: new Date("2024-9-9"),
    applicationStatus: "Unreviewed",
    isEdited: true,
    activeEmail: "carlobautista@gmail.com",
    lastName: "Bautista",
    firstName: "Carlo",
    age: 21,
    gender: "Male",
    nationality: "Filipino",
    religion: "Catholic",
    birthdate: "2003-12-01",
    birthplace: "Taguig City",
    civilStatus: "Single",
    birthRank: "4th",
    numBrothers: 2,
    numSisters: 0,
    numCITBrothersSisters: 0,
    homeAddress: "678 Pine St., Taguig City",
    cityAddress: "789 Cedar Ave., Taguig City",
    facebookURL: "https://facebook.com/carlobautista",
    mobileNumber: "09124445566",
    fatherName: "Bautista, Ronald F.",
    fatherAge: 48,
    fatherBirthplace: "Taguig City",
    fatherNationality: "Filipino",
    fatherReligion: "Catholic",
    fatherEducation: "College Graduate",
    fatherOccupation: "Police Officer",
    motherName: "Bautista, Celia G.",
    motherAge: 46,
    motherBirthplace: "Makati City",
    motherNationality: "Filipino",
    motherReligion: "Catholic",
    motherEducation: "College Graduate",
    motherOccupation: "Nurse",
    prevCourse: "BSA",
    lastSchool: "NOP University",
    schoolYear: "2022",
    schoolType: "Private",
    prevSchoolAddress: "789 Red St., Taguig City",
    hsSchoolName: "NOP High School",
    hsSchoolAddress: "Taguig City",
    hsYearGraduated: "2020",
    elemSchoolName: "VWX Elementary School",
    elemSchoolAddress: "Taguig City",
    elemYearGraduated: "2016",
    progChoice1: "BSA",
    progChoice2: "BSAcT",
    progChoice3: "BSE",
    contactName: "Dela Cruz, Maria S.",
    relation: "Neighbor",
    contactAddress: "654 Pine St., Taguig City",
    contactNumber: "09115557788",
    evalSheet: null,
    jobDescription: null,
    tor: null,
    hsForm: null,
    transferCred: null,
    marriageCert: null,
    employmentCert: null,
    businessProof: null,
    applicantType: "ETEEAP",
    missingDocs: "None",
    photoWithID: null,
    examSet: "Set B",
    firstQuestion: "Ambition inspires people to push beyond their limits.",
    secondQuestion: "Honesty is the foundation of trust and respect.",
    thirdQuestion: "Our life’s journey is determined by the choices we make.",
    fourthQuestion: "Reading opens up new perspectives and knowledge.",
    fifthQuestion: "Practical experience builds a stronger understanding of theoretical concepts."
  }
  
  // Additional entries...
];
